import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='mx-4 md:mx-34 xl:mx-72 bg-[#534292]'>{children}</body>
    </html>
  );
}
